### ISSUE TITLE
 Could not load file or assembly 'socksify.dll' or one of its dependencies

### ISSUE THREAD

**Issue by oligodar** [wiresock/proxifyre#16]
Hi, after running it reports: 

 An exception occurred, System.IO.FileNotFoundException: Could not load file or assembly 'socksify.dll' or one of its dependencies. The specified module could not be found.
File name: 'socksify.dll'
   at ProxiFyre.ProxiFyreService.Start()
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()

![image](https://github.com/wiresock/proxifyre/assets/17950507/bf813405-1ecd-4026-98d7-31552b00e1eb)

System is Windows 11 22H2, I tried to install Microsoft VC_redist.x64 (1) (2015-2022). It did not help.

**Comment by oligodar** [comment]
I have managed to work it out. 

These applications must be installed in this order>

01.VC_redist.x64.exe 
02.Windows.Packet.Filter.3.4.3.1.x64 (1).msi
03.ProxiFyre-v1.0.18-x64.zip
