### ISSUE TITLE
Fail to launch

### ISSUE THREAD

**Issue by AR45H** [wiresock/proxifyre#20]
Running the exe results in a commandline window flashing for a sec and then closing without launching the program. Here's the log. Tried with admin too, no result.

```
Configuration Result:
[Success] Name ProxiFyreService
[Success] DisplayName ProxiFyre Service
[Success] Description ProxiFyre - SOCKS5 Proxifier Service
[Success] ServiceName ProxiFyreService
Topshelf v4.3.0.0, .NET Framework 4.8.4515.0 (4.0.30319.42000)
Topshelf.Hosts.ConsoleRunHost Error: 0 : An exception occurred, System.IO.FileNotFoundException: Could not find file 'D:\Users\AR45H\Desktop\ProxiFyre-v1.0.18-x64\app-config.json'.
File name: 'D:\Users\AR45H\Desktop\ProxiFyre-v1.0.18-x64\app-config.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ProxiFyre.ProxiFyreService.Start()
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()
```

**Comment by AR45H** [comment]
Thanks for the reply wiresock, I assumed as much but I did not find any reference to it anywhere either in the github repo page or on your website ntkernel.com
Could you kindly point me in the correct direction to a doc/help/setup page or something?
Thanks

**Comment by AR45H** [comment]
I'm so sorry, you're completely right. It appears my github account has been limited in some way. For the past few weeks repos would look empty to me, at first I thought maybe github was changing UI or something, but after logging out I noticed I've been limited because this is what I've been seeing for the past few weeks:
![image](https://github.com/wiresock/proxifyre/assets/20746569/ee27da24-9f6d-43d6-b7e7-05d0a236eb02)
